pipeline {
      agent any
	  parameters {
        string(name: 'NAME', description: 'Please tell me your project name')
		 string(defaultValue: env.VERSION, description: 'What Version?', name: 'VERSION')
        //choice(name: 'APPNMAE', choices: ['TrackApp', 'BIAppp'], description: 'Choose Application')
    }
      stages {
            stage('Track Build Application') {
                  steps {
						echo env.VERSION
                        echo '<<<Starting Build>>>'
						//bat 'gradlew.bat build test'  					
                        echo '<<<End Build>>>'
                  }
				  post {
						success {
							echo "Now Archiving the Artifacts...."
							//archiveArtifacts artifacts: '**/*.war'
						}
					}				  
				  
            }
			stage('Track Test Application') {
				steps {
					echo "....Testing In-Progress...."
				}
			}
            stage('Track Deploy in Staging Envoirnment2') {
                  steps {                        
						echo '<<<Starting Staging Deployment: copyArtifacts>>>'
						
						//copyArtifacts(projectName: "$JOB_NAME", selector: lastSuccessful(stable: true), optional: true)
						echo '<<<Starting Staging Deployment: deploy adapters>>>'
						//deploy adapters: [tomcat9(url: 'http://localhost:8082',
						//	credentialsId: 'tomcat9')], 
						//	war: '**/*.war',
						//	contextPath: 'app7'
										
                        echo '<<<End Staging Deployment>>>'
                  }
            }
            
      }
}